# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Materias',
            field=models.ManyToManyField(to='principal.Materia'),
        ),
    ]
