# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0004_remove_alumno_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
