# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_remove_alumno_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='NoControl',
            field=models.IntegerField(),
        ),
    ]
