# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_alumno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Materias',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Materias',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Materia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='materia',
            name='Docente',
        ),
        migrations.AddField(
            model_name='materia',
            name='Docente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Docente'),
            preserve_default=False,
        ),
    ]
