# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_auto_20180522_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Materias',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Materias',
            field=models.ManyToManyField(to='principal.Materia'),
        ),
    ]
