# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_auto_20180524_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Clases',
            field=models.ManyToManyField(to='principal.Clase'),
        ),
    ]
