# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_auto_20180524_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Clases',
            field=models.ManyToManyField(null=True, to='principal.Clase'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Materias',
            field=models.ManyToManyField(null=True, to='principal.Materia'),
        ),
    ]
