# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('NoControl', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('NoAula', models.IntegerField(primary_key=True, serialize=False)),
                ('Edificio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('IdDocente', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('IdMateria', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Semestre', models.IntegerField()),
                ('Nombre', models.CharField(max_length=50)),
                ('aula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Aula')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Materias',
            field=models.ManyToManyField(blank=True, null=True, to='principal.Materia'),
        ),
    ]
