# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20180520_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='Docente',
            field=models.ManyToManyField(to='principal.Docente'),
        ),
    ]
