# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20180521_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='NoControl',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
