# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20180521_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='NoControl',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
