# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_alumno_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Materias',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
