# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0011_auto_20180521_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('NoControl', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Materias', models.ManyToManyField(to='principal.Materia')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
