# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_materia_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('IdClase', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Hora', models.CharField(max_length=15)),
                ('Contador', models.IntegerField()),
                ('Aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Aula')),
            ],
        ),
        migrations.RemoveField(
            model_name='materia',
            name='Docente',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='Hora',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='aula',
        ),
        migrations.AddField(
            model_name='alumno',
            name='Semestre',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='Materias',
            field=models.ManyToManyField(to='principal.Materia'),
        ),
        migrations.AddField(
            model_name='clase',
            name='Docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Docente'),
        ),
        migrations.AddField(
            model_name='clase',
            name='Materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.Materia'),
        ),
    ]
