# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_auto_20180524_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Clases',
            field=models.ManyToManyField(to='principal.Clase'),
        ),
    ]
